import { access, readdir, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { join, parse } from "node:path";
import { ALL_FORMATS, FilePathSource, Input } from "mediabunny";

const FPS = 30;
const WIDTH = 1080;
const HEIGHT = 1920;

const VIDEO_EXTENSIONS = [".mov", ".mp4", ".m4v", ".webm"];

const publicDir = join(process.cwd(), "public");
const sourceDir = join(publicDir, "day0");
const captionsDir = join(publicDir, "captions");
const outFile = join(process.cwd(), "src", "Day0.tsx");

// The seven sections of the Day 0 script, keyed by the number prefix on the
// filename. Sections 1, 4 and 7 carry no dialogue that needs subtitling
// beyond what the clip itself says.
const SECTIONS = {
  "01": { name: "V1 — físico actual", silent: true },
  "02": { name: "V2 — este soy yo ahora mismo", silent: false },
  "03": { name: "V3 — qué pasó", silent: false },
  "04": { name: "V4 — vídeos antiguos", silent: true },
  "05": { name: "V5 — el reto de 90 días", silent: false },
  "06": { name: "V6 — qué voy a documentar", silent: false },
  "07": { name: "V7 — el final", silent: false },
};

const probe = async (relPath) => {
  const input = new Input({
    formats: ALL_FORMATS,
    source: new FilePathSource(join(publicDir, relPath)),
  });
  const duration = await input.computeDuration();
  const track = await input.getPrimaryVideoTrack();
  return {
    relPath,
    duration,
    width: track?.displayWidth ?? null,
    height: track?.displayHeight ?? null,
  };
};

const hasCaptions = async (base) => {
  try {
    await access(join(captionsDir, `${base}.json`), constants.R_OK);
    return true;
  } catch {
    return false;
  }
};

const sectionJsx = ({ relPath, base, durationInFrames, name, captioned }) => {
  const subtitles = captioned
    ? `\n          <Subtitles captionFile=${JSON.stringify(base)} trimBefore={0} />`
    : "";

  return `        <TransitionSeries.Sequence
          name=${JSON.stringify(name)}
          durationInFrames={${durationInFrames}}
        >
          <Video
            src={staticFile(${JSON.stringify(relPath)})}
            trimBefore={0}
            objectFit="cover"
            style={fill}
          />${subtitles}
        </TransitionSeries.Sequence>`;
};

const buildFile = (sections) => {
  const total = sections.reduce((sum, s) => sum + s.durationInFrames, 0);
  const needsSubtitles = sections.some((s) => s.captioned);

  return `import { Video } from "@remotion/media";
import { TransitionSeries } from "@remotion/transitions";
import { AbsoluteFill, Composition, staticFile } from "remotion";${
    needsSubtitles ? '\nimport { Subtitles } from "./Subtitles";' : ""
  }

// Generated by \`npm run scan:day0\`. Rerunning overwrites it, so once the
// edit is being shaped by hand, copy it to another file first.
//
// Every clip currently plays in full. Trimming happens by dragging the clip
// edges in the Studio timeline, which writes the new durations back here.

const fill: React.CSSProperties = {
  width: "100%",
  height: "100%",
};

export const Day0: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: "black" }}>
      <TransitionSeries name="Day 0">
${sections.map(sectionJsx).join("\n")}
      </TransitionSeries>
    </AbsoluteFill>
  );
};

export const Day0Composition: React.FC = () => {
  return (
    <Composition
      id="Day0"
      component={Day0}
      durationInFrames={${total}}
      fps={${FPS}}
      width={${WIDTH}}
      height={${HEIGHT}}
    />
  );
};
`;
};

const main = async () => {
  let entries;
  try {
    entries = await readdir(sourceDir);
  } catch {
    console.error(`Expected your numbered clips in ${sourceDir}`);
    console.error(`Name them 01.mov, 02.mov ... 07.mov`);
    process.exit(1);
  }

  const files = entries
    .filter((name) =>
      VIDEO_EXTENSIONS.some((ext) => name.toLowerCase().endsWith(ext)),
    )
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

  if (files.length === 0) {
    console.error(`No video files in ${sourceDir}`);
    process.exit(1);
  }

  const sections = [];

  for (const file of files) {
    const base = parse(file).name.slice(0, 2);
    const meta = await probe(`day0/${file}`);
    const section = SECTIONS[base];
    const captioned = !section?.silent && (await hasCaptions(parse(file).name));

    sections.push({
      relPath: meta.relPath,
      base: parse(file).name,
      name: section?.name ?? file,
      duration: meta.duration,
      durationInFrames: Math.max(1, Math.round(meta.duration * FPS)),
      captioned,
      width: meta.width,
      height: meta.height,
    });
  }

  await writeFile(outFile, buildFile(sections));

  console.log(`Day 0 timeline — ${sections.length} sections\n`);
  for (const s of sections) {
    console.log(
      `  ${s.relPath.padEnd(26)} ${s.duration.toFixed(1).padStart(6)}s  ` +
        `${s.width}x${s.height}  ` +
        `${s.captioned ? "subtitled" : "no subtitles"}  ${s.name}`,
    );
  }

  const total = sections.reduce((sum, s) => sum + s.durationInFrames, 0);
  console.log(`\nWrote src/Day0.tsx — ${(total / FPS).toFixed(1)}s total.`);

  const missing = sections.filter(
    (s) => !s.captioned && !SECTIONS[s.base.slice(0, 2)]?.silent,
  );
  if (missing.length > 0) {
    console.log(`\nNo captions yet for: ${missing.map((s) => s.base).join(", ")}`);
    console.log(`Run \`npm run transcribe\` first, then rerun this.`);
  }
};

await main();
