import { readdir, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { ALL_FORMATS, FilePathSource, Input } from "mediabunny";

const FPS = 30;
const WIDTH = 1080;
const HEIGHT = 1920;
const MAX_CLIP_SECONDS = 2.5;

const VIDEO_EXTENSIONS = [".mov", ".mp4", ".m4v", ".webm"];

const publicDir = join(process.cwd(), "public");
const outFile = join(process.cwd(), "src", "Reel.tsx");

const probe = async (fileName) => {
  const input = new Input({
    formats: ALL_FORMATS,
    source: new FilePathSource(join(publicDir, fileName)),
  });

  const duration = await input.computeDuration();
  const track = await input.getPrimaryVideoTrack();

  return {
    fileName,
    duration,
    width: track?.displayWidth ?? null,
    height: track?.displayHeight ?? null,
  };
};

const clipJsx = ({ fileName, durationInFrames, trimBefore }) =>
  `      <TransitionSeries.Sequence
        name="${fileName}"
        durationInFrames={${durationInFrames}}
      >
        <Video
          src={staticFile(${JSON.stringify(fileName)})}
          trimBefore={${trimBefore}}
          objectFit="cover"
          style={fill}
        />
      </TransitionSeries.Sequence>`;

const buildFile = (clips) => {
  const total = clips.reduce((sum, clip) => sum + clip.durationInFrames, 0);

  return `import { Video } from "@remotion/media";
import { TransitionSeries } from "@remotion/transitions";
import { AbsoluteFill, Composition, staticFile } from "remotion";

// Generated by \`npm run scan\`. Safe to edit by hand — rerunning overwrites it.
// Drag clip edges in the Studio timeline and the numbers below update themselves.

const fill: React.CSSProperties = {
  width: "100%",
  height: "100%",
};

export const Reel: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: "black" }}>
      <TransitionSeries name="Reel">
${clips.map(clipJsx).join("\n")}
      </TransitionSeries>
    </AbsoluteFill>
  );
};

export const ReelComposition: React.FC = () => {
  return (
    <Composition
      id="Reel"
      component={Reel}
      durationInFrames={${total}}
      fps={${FPS}}
      width={${WIDTH}}
      height={${HEIGHT}}
    />
  );
};
`;
};

const main = async () => {
  const entries = await readdir(publicDir);
  const videoFiles = entries
    .filter((name) =>
      VIDEO_EXTENSIONS.some((ext) => name.toLowerCase().endsWith(ext)),
    )
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

  if (videoFiles.length === 0) {
    console.error(`No video files found in ${publicDir}`);
    console.error(`Looked for: ${VIDEO_EXTENSIONS.join(", ")}`);
    process.exit(1);
  }

  const probed = await Promise.all(videoFiles.map(probe));

  const clips = probed.map((clip) => ({
    ...clip,
    trimBefore: 0,
    durationInFrames: Math.max(
      1,
      Math.round(Math.min(clip.duration, MAX_CLIP_SECONDS) * FPS),
    ),
  }));

  await writeFile(outFile, buildFile(clips));

  const totalFrames = clips.reduce((sum, c) => sum + c.durationInFrames, 0);

  console.log(`Found ${clips.length} clips in public/\n`);
  for (const clip of clips) {
    const orientation =
      clip.width && clip.height
        ? clip.height > clip.width
          ? "vertical"
          : "landscape"
        : "unknown";
    console.log(
      `  ${clip.fileName.padEnd(44)} ${clip.duration.toFixed(1)}s  ` +
        `${clip.width}x${clip.height} ${orientation}  ` +
        `-> using ${(clip.durationInFrames / FPS).toFixed(1)}s`,
    );
  }
  console.log(
    `\nWrote ${relative(process.cwd(), outFile)} — ` +
      `${(totalFrames / FPS).toFixed(1)}s total at ${WIDTH}x${HEIGHT}.`,
  );
};

await main();
