import { readdir, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { ALL_FORMATS, FilePathSource, Input } from "mediabunny";

const FPS = 30;
const WIDTH = 1080;
const HEIGHT = 1920;
const MAX_CLIP_SECONDS = 2.5;

const VIDEO_EXTENSIONS = [".mov", ".mp4", ".m4v", ".webm"];

// Anything matching this is treated as a style reference, not as footage.
const REFERENCE_PATTERN = /reference/i;

const publicDir = join(process.cwd(), "public");
const reelFile = join(process.cwd(), "src", "Reel.tsx");
const clipsFile = join(process.cwd(), "src", "clips.ts");

const collectVideos = async (dir, prefix = "") => {
  const entries = await readdir(dir, { withFileTypes: true });
  const found = [];

  for (const entry of entries) {
    const relPath = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      found.push(...(await collectVideos(join(dir, entry.name), relPath)));
    } else if (
      VIDEO_EXTENSIONS.some((ext) => entry.name.toLowerCase().endsWith(ext))
    ) {
      found.push(relPath);
    }
  }

  return found;
};

const probe = async (relPath) => {
  const input = new Input({
    formats: ALL_FORMATS,
    source: new FilePathSource(join(publicDir, relPath)),
  });

  const duration = await input.computeDuration();
  const track = await input.getPrimaryVideoTrack();

  return {
    relPath,
    duration,
    width: track?.displayWidth ?? null,
    height: track?.displayHeight ?? null,
  };
};

const clipJsx = ({ relPath, durationInFrames, trimBefore }) =>
  `      <TransitionSeries.Sequence
        name=${JSON.stringify(relPath)}
        durationInFrames={${durationInFrames}}
      >
        <Video
          src={staticFile(${JSON.stringify(relPath)})}
          trimBefore={${trimBefore}}
          objectFit="cover"
          style={fill}
        />
      </TransitionSeries.Sequence>`;

const buildReel = (clips) => {
  const total = clips.reduce((sum, clip) => sum + clip.durationInFrames, 0);

  return `import { Video } from "@remotion/media";
import { TransitionSeries } from "@remotion/transitions";
import { AbsoluteFill, Composition, staticFile } from "remotion";

// Generated by \`npm run scan\`. Safe to edit by hand — rerunning overwrites it.
// Drag clip edges in the Studio timeline and the numbers below update themselves.

const fill: React.CSSProperties = {
  width: "100%",
  height: "100%",
};

export const Reel: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: "black" }}>
      <TransitionSeries name="Reel">
${clips.map(clipJsx).join("\n")}
      </TransitionSeries>
    </AbsoluteFill>
  );
};

export const ReelComposition: React.FC = () => {
  return (
    <Composition
      id="Reel"
      component={Reel}
      durationInFrames={${total}}
      fps={${FPS}}
      width={${WIDTH}}
      height={${HEIGHT}}
    />
  );
};
`;
};

const buildClipsManifest = (clips) =>
  `// Generated by \`npm run scan\`. Used by the ContactSheet preview.

export type Clip = {
  src: string;
  durationInSeconds: number;
  width: number | null;
  height: number | null;
};

export const clips: Clip[] = ${JSON.stringify(
    clips.map((c) => ({
      src: c.relPath,
      durationInSeconds: Number(c.duration.toFixed(2)),
      width: c.width,
      height: c.height,
    })),
    null,
    2,
  )};
`;

const main = async () => {
  const allVideos = (await collectVideos(publicDir)).sort((a, b) =>
    a.localeCompare(b, undefined, { numeric: true }),
  );

  const references = allVideos.filter((p) => REFERENCE_PATTERN.test(p));
  const footage = allVideos.filter((p) => !REFERENCE_PATTERN.test(p));

  if (footage.length === 0) {
    console.error(`No footage found under ${publicDir}`);
    console.error(`Looked for: ${VIDEO_EXTENSIONS.join(", ")}`);
    process.exit(1);
  }

  const probed = await Promise.all(footage.map(probe));

  const clips = probed.map((clip) => ({
    ...clip,
    trimBefore: 0,
    durationInFrames: Math.max(
      1,
      Math.round(Math.min(clip.duration, MAX_CLIP_SECONDS) * FPS),
    ),
  }));

  await writeFile(reelFile, buildReel(clips));
  await writeFile(clipsFile, buildClipsManifest(clips));

  console.log(`Found ${clips.length} clips\n`);
  for (const clip of clips) {
    const orientation =
      clip.width && clip.height
        ? clip.height > clip.width
          ? "vertical"
          : "landscape"
        : "unknown";
    console.log(
      `  ${clip.relPath.padEnd(46)} ${clip.duration.toFixed(1).padStart(6)}s  ` +
        `${String(clip.width).padStart(4)}x${String(clip.height).padEnd(4)} ` +
        `${orientation.padEnd(9)} -> using ${(clip.durationInFrames / FPS).toFixed(1)}s`,
    );
  }

  if (references.length > 0) {
    console.log(`\nReference (excluded from the reel):`);
    for (const ref of references) {
      const meta = await probe(ref);
      console.log(
        `  ${meta.relPath.padEnd(46)} ${meta.duration.toFixed(1).padStart(6)}s  ` +
          `${meta.width}x${meta.height}`,
      );
    }
  }

  const totalFrames = clips.reduce((sum, c) => sum + c.durationInFrames, 0);
  console.log(
    `\nWrote ${relative(process.cwd(), reelFile)} — ` +
      `${(totalFrames / FPS).toFixed(1)}s total at ${WIDTH}x${HEIGHT}.`,
  );
};

await main();
