// Generated by `npm run scan`. Used by the ContactSheet preview.

export type Clip = {
  src: string;
  durationInSeconds: number;
  width: number | null;
  height: number | null;
};

export const clips: Clip[] = [];

// Style references — sampled by the ReferenceStrip composition, never edited
// into the reel.
export const references: Clip[] = [];
