import type { Caption, TikTokPage } from "@remotion/captions";
import { createTikTokStyleCaptions } from "@remotion/captions";
import { useCallback, useEffect, useMemo, useState } from "react";
import {
  AbsoluteFill,
  Sequence,
  staticFile,
  useCurrentFrame,
  useDelayRender,
  useVideoConfig,
} from "remotion";

// Spanish subtitles generated by `npm run transcribe`. The dialogue is never
// translated — these render exactly what was said.

const SWITCH_CAPTIONS_EVERY_MS = 1100;
const HIGHLIGHT = "#FFD400";

// Sits above the platform's own caption/username UI, which eats the bottom
// ~15% of a Reel.
const BOTTOM_OFFSET = 420;

const CaptionPage: React.FC<{ page: TikTokPage }> = ({ page }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const absoluteTimeMs = page.startMs + (frame / fps) * 1000;

  return (
    <AbsoluteFill
      style={{
        justifyContent: "flex-end",
        alignItems: "center",
        paddingBottom: BOTTOM_OFFSET,
        paddingLeft: 70,
        paddingRight: 70,
      }}
    >
      <div
        style={{
          fontFamily: "Helvetica, Arial, sans-serif",
          fontWeight: 900,
          fontSize: 68,
          lineHeight: 1.15,
          textAlign: "center",
          whiteSpace: "pre-wrap",
          textShadow:
            "0 4px 18px rgba(0,0,0,0.9), 0 0 6px rgba(0,0,0,0.9)",
          letterSpacing: -1,
        }}
      >
        {page.tokens.map((token, tokenIndex) => {
          const isActive =
            token.fromMs <= absoluteTimeMs && token.toMs > absoluteTimeMs;

          return (
            <span
              key={`${token.fromMs}-${tokenIndex}`}
              style={{ color: isActive ? HIGHLIGHT : "white" }}
            >
              {token.text}
            </span>
          );
        })}
      </div>
    </AbsoluteFill>
  );
};

export const Subtitles: React.FC<{
  /** Basename of the JSON in public/captions, e.g. "02" for 02.json */
  captionFile: string;
  /** Frames trimmed off the head of the clip, so subtitles stay in sync. */
  trimBefore?: number;
}> = ({ captionFile, trimBefore = 0 }) => {
  const { fps } = useVideoConfig();
  const [captions, setCaptions] = useState<Caption[] | null>(null);
  const { delayRender, continueRender, cancelRender } = useDelayRender();
  const [handle] = useState(() => delayRender());

  const fetchCaptions = useCallback(async () => {
    try {
      const response = await fetch(staticFile(`captions/${captionFile}.json`));
      setCaptions(await response.json());
      continueRender(handle);
    } catch (e) {
      cancelRender(e);
    }
  }, [captionFile, continueRender, cancelRender, handle]);

  useEffect(() => {
    fetchCaptions();
  }, [fetchCaptions]);

  // Timings come from the untrimmed source, so shift them by whatever the
  // edit cut off the front.
  const offsetMs = (trimBefore / fps) * 1000;

  const { pages } = useMemo(() => {
    if (!captions) {
      return { pages: [] as TikTokPage[] };
    }
    return createTikTokStyleCaptions({
      captions: captions.map((caption) => ({
        ...caption,
        startMs: caption.startMs - offsetMs,
        endMs: caption.endMs - offsetMs,
        timestampMs:
          caption.timestampMs === null ? null : caption.timestampMs - offsetMs,
      })),
      combineTokensWithinMilliseconds: SWITCH_CAPTIONS_EVERY_MS,
    });
  }, [captions, offsetMs]);

  if (!captions) {
    return null;
  }

  return (
    <AbsoluteFill>
      {pages.map((page, index) => {
        const nextPage = pages[index + 1] ?? null;
        const startFrame = (page.startMs / 1000) * fps;
        const endFrame = Math.min(
          nextPage ? (nextPage.startMs / 1000) * fps : Infinity,
          startFrame + (SWITCH_CAPTIONS_EVERY_MS / 1000) * fps,
        );
        const durationInFrames = endFrame - startFrame;

        if (durationInFrames <= 0 || endFrame <= 0) {
          return null;
        }

        return (
          <Sequence
            key={index}
            from={Math.max(0, startFrame)}
            durationInFrames={durationInFrames}
          >
            <CaptionPage page={page} />
          </Sequence>
        );
      })}
    </AbsoluteFill>
  );
};
